on:
  release:
    types: [created]
jobs:
  build:
    runs-on: windows-2016
    steps:
      - uses: actions/setup-node@master
        with:
           node-version: "14.x" 
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: "Setup NASM for windows"
        uses: ilammy/setup-nasm@v1
      - name: Install Python2 for windows
        uses: actions/setup-python@v1
        with:
          python-version: '2.x'
     
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - name: Build Qode binary
        run: node build.js
        env:
          SYNC_GIT_SUBMODULE: 1
          
      - name: Compress files
        uses: master-atul/tar-action@v1.0.2
        id: compress
        with:
          command: c
          cwd: ./node/out/Release
          files: |
            ./qode.exe
            ./qode.lib
            ./qode.exp
          outPath: qode-win32-x64-${{github.event.release.tag_name}}.tar.gz
      
      - uses: actions/upload-artifact@v1
        with:
          name: qode-win32-x64-${{github.event.release.tag_name}}.tar.gz
          path: qode-win32-x64-${{github.event.release.tag_name}}.tar.gz

      - name: Release
        uses: softprops/action-gh-release@master
        with:
          files: qode-win32-x64-${{github.event.release.tag_name}}.tar.gz
          tag_name: ${{ github.event.release.tag_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}